version: 2

project_name: shitpost

before:
  hooks:
    - go mod tidy

builds:
  - id: bot
    main: ./main.go
    binary: bot
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

sboms:
  - artifacts: archive
    cmd: syft
    args: ["$artifact", "--output", "spdx-json=$document"]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: bupd
    name: shitpost
  draft: false
  prerelease: auto
